version: '3.8'

services:
  mysqldb:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: registro
    ports:
      - 3306:3306

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: mysql://root:root@mysqldb:3306/registro
    depends_on:
      - mysqldb
    ports:
      - 3000:3000